# Generated by Django 5.0.3 on 2024-03-16 16:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField()),
                ('artist', models.CharField()),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
            ],
        ),
    ]
