# Generated by Django 5.0.3 on 2024-03-17 21:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField()),
                ('title', models.CharField()),
                ('artist', models.CharField()),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField()),
                ('title', models.CharField()),
                ('director', models.CharField()),
                ('cinematographer', models.CharField()),
                ('writer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('just_watch_link', models.CharField(verbose_name='JustWatch Link')),
                ('wiki_link', models.CharField(verbose_name='Wikipedia Link')),
                ('imdb_link', models.CharField(verbose_name='IMDB Link')),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('owner', models.CharField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selections.album')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selections.movie')),
            ],
        ),
    ]
