# Generated by Django 5.0.3 on 2024-03-15 21:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('director', models.CharField()),
                ('cinematographer', models.CharField()),
                ('writer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('just_watch_link', models.CharField()),
                ('wiki_link', models.CharField()),
                ('imdb_link', models.CharField()),
            ],
        ),
    ]
