# Generated by Django 5.0.3 on 2024-03-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.CharField(default='fix_me'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_link',
            field=models.CharField(verbose_name='IMDB Link'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='just_watch_link',
            field=models.CharField(verbose_name='JustWatch Link'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='wiki_link',
            field=models.CharField(verbose_name='Wikipedia Link'),
        ),
    ]
